[package]
name = "lisp-core"
version = "0.1.0"
authors = ["mbilling <flkazemakase@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexpr = "0.2"
rustyline = "5.0"
